% RANDOMVARIABLES_RAYLEIGH_DISTRIBUTION
%
% Author: Dick Carrillo Melgarejo
%
% Date: 23/July/2020
%
% Tool: Matlab 2020a
%
% Simulated and analytical version of Rice Distribution
% The random variable "R" defined by Rice Distribution is generated by
% the following equation R = SQRT(X^2+Y^2), where X and Y are independent
% Gaussian Random variables with u1 and u2 mean (respectively) and Variance sigma^2.
% So, in communications, X is the real part of a complex number and Y
% is the imaginary part of the same complex number. This complex number is
% the base band representation of a Rice channel. In communications the
% random variable R represents the module of the base band signal (complex
% number).
close all
clear all

%% Simulation Version
N = 100000;
sigma = 1/sqrt(2);
K = 1;
% Rice parameters


% we will get the rice simulation based on parameter "K", so, for this
% reason we consider that u1 and u2 are equal.
v=sqrt(2*K*sigma^2);
u1=v/sqrt(2);
u2=u1;

%u1 = 2;
%u2 = 9;
%v=sqrt(u1^2 + u2^2);
%
% K = v^2/(2*sigma^2);
hr = sigma * (randn(1,N) + sqrt(-1) * randn(1,N))+(u1 + sqrt(-1) * u2);
display(['The Variance of the band base representation of the channel is '...
    num2str(var(hr))])
display(['The Mean of the band base representation of the channel is '...
    num2str(mean(hr))])
[a,b] = hist(abs(hr),50);
pdfSim=a./trapz(b,a);
stem(b,pdfSim)


%% Theoretical Version
hold on
x = min(b):0.01:max(b);
p = ricepdf(x,K,sigma);
plot(x,p,'r')



%% auxiliar function

function y = ricepdf(x, k, s)
s2 = s.^2; % (neater below)

v=sqrt(2*k*s2);

try
    y = (x ./ s2) .*...
        exp(-0.5 * (x.^2 + v.^2) ./ s2) .*...
        besseli(0, x .* v ./ s2);
        % besseli(0, ...) is the zeroth order modified Bessel function of
        % the first kind. (see help bessel)
    y(x <= 0) = 0;
catch
    error('ricepdf:InputSizeMismatch',...
        'Non-scalar arguments must match in size.');
end
end