% RANDOMVARIABLES_RAYLEIGH_DISTRIBUTION
%
% Author: Dick Carrillo Melgarejo
%
% Date: 23/July/2020
%
% Tool: Matlab 2020a
%
% Simulated and analytical version of Rayleigh Distribution
% The random variable "R" defined by Rayleigh Distribution is generated by
% the following equation R = SQRT(X^2+Y^2), where X and Y are independent
% Gaussian Random variables with zero mean and Variance sigma^2.
% So, in communications, X is the real part of a complex number and Y
% is the imaginary part of the same complex number. This complex number is
% the base band representation of a Rayleigh channel. In communications the
% random variable R represents the module of this band base signal (complex
% number).
close all
clear all

%% Simulation Version
N = 100000;
sigma = 1/sqrt(2);
hr = sigma * (randn(1,N) + sqrt(-1) * randn(1,N));
display(['The Variance of the band base representation of the channel is '...
    num2str(var(hr))])
display(['The Mean of the band base representation of the channel is '...
    num2str(mean(hr))])
[a,b] = hist(abs(hr),50);
pdfSim=a./trapz(b,a);
stem(b,pdfSim)


%% Theoretical Version
hold on
x = min(b):0.01:max(b);
p = raylpdf(x,sigma);
plot(x,p,'r')